# Generated by Django 5.1.5 on 2025-01-22 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0003_staff_job_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='vehicle_type',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='dealership_id',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='position',
        ),
    ]
