# Generated by Django 5.1.5 on 2025-01-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0004_remove_driver_vehicle_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('american', 'American'), ('german', 'German')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('type', models.CharField(default='sedan', max_length=50)),
                ('transmission', models.CharField(default='automatic', max_length=50)),
                ('gas', models.CharField(default='50', max_length=50)),
            ],
        ),
    ]
