# Generated by Django 5.1.5 on 2025-01-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0006_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('american', 'American'), ('german', 'German'), ('japanese', 'Japanese'), ('italian', 'Italian')], max_length=20),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
