# Generated by Django 5.1.5 on 2025-01-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0003_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='power',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.CharField(default='2020', max_length=4),
        ),
    ]
